services:
  flask-app:
    build:
      context: .
    container_name: flask-app
    restart: always
    depends_on:
      - mysql
    environment:
      FLASK_ENV: development
    ports:
      - '5001:5000'
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    networks:
      - app-network
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
<<<<<<< HEAD
      - ./docker/scripts/create-db.sql:/docker-entrypoint-initdb.d/create-db.sql
=======
    # entrypoint: /docker/scripts/create-db.sql
>>>>>>> 6034dae (fix(predict_service): prevent loading models before they are created)

  phpmyadmin:
    image: phpmyadmin:5.2
    container_name: phpmyadmin
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      PMA_HOST: mysql
    ports:
      - '8080:80'
    networks:
      - app-network
    depends_on:
      - mysql

networks:
  app-network:

volumes:
  mysql-data:
